<div class='container'>
    <h2>Body Measurment</h2>
    <h5>Jacket</h5>
    <hr>

    <dl cloth-id="3">
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Neck">Neck</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="30" sizeto="66" class="range">(Range30-66)</span>
            <span data-id="10265" sizefrom="30" sizeto="66" class="range" style="display: none;">(Range11.81-25.98)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="30" sizefrominch="11.81" sizetoinch="25.98" sizeto="66" id="10101" inchvalue="0.00" cmvalue="" data-map="sizeMap" title="30-66">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Chest">Chest</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="66" sizeto="186" class="range">(Range66-186)</span>
            <span data-id="10265" sizefrom="66" sizeto="186" class="range" style="display: none;">(Range25.98-73.23)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="66" sizefrominch="25.98" sizetoinch="73.23" sizeto="186" id="10102" inchvalue="" cmvalue="" data-map="sizeMap" title="66-186">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on"><span class="s1 star" title="Stomach">Stomach</span><span class="solon">:</span>
            <span data-id="10266" sizefrom="58" sizeto="185" class="range">(Range58-185)</span>
            <span data-id="10265" sizefrom="58" sizeto="185" class="range" style="display: none;">(Range22.83-72.83)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="58" sizefrominch="22.83" sizetoinch="72.83" sizeto="185" id="10105" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Seat">Seat</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="68" sizeto="200" class="range">(Range68-200)</span>
            <span data-id="10265" sizefrom="68" sizeto="200" class="range" style="display: none;">(Range26.77-78.74)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="68" sizefrominch="26.77" sizetoinch="78.74" sizeto="200" id="10108" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Bicep">Bicep</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="19" sizeto="74" class="range">(Range19-74)</span>
            <span data-id="10265" sizefrom="19" sizeto="74" class="range" style="display: none;">(Range7.48-29.13)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="19" sizefrominch="7.48" sizetoinch="29.13" sizeto="74" id="10110" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Shoulder">Shoulder</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="31" sizeto="72" class="range">(Range31-72)</span>
            <span data-id="10265" sizefrom="31" sizeto="72" class="range" style="display: none;">(Range12.20-28.35)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="31" sizefrominch="12.20" sizetoinch="28.35" sizeto="72" id="10111" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Sleeve(L)">Sleeve(L)</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="25" sizeto="85" class="range">(Range25-85)</span>
            <span data-id="10265" sizefrom="25" sizeto="85" class="range" style="display: none;">(Range9.84-33.46)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="25" sizefrominch="9.84" sizetoinch="33.46" sizeto="85" id="10113" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Sleeve( R )">Sleeve( R )</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="25" sizeto="85" class="range">(Range25-85)</span>
            <span data-id="10265" sizefrom="25" sizeto="85" class="range" style="display: none;">(Range9.84-33.46)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="25" sizefrominch="9.84" sizetoinch="33.46" sizeto="85" id="10114" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Front Shoulder">Front Shoulder</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="29" sizeto="68" class="range">(Range29-68)</span>
            <span data-id="10265" sizefrom="29" sizeto="68" class="range" style="display: none;">(Range11.42-26.77)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="29" sizefrominch="11.42" sizetoinch="26.77" sizeto="68" id="10115" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Nape to waist">Nape to waist</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="29" sizeto="63" class="range">(Range29-63)</span>
            <span data-id="10265" sizefrom="29" sizeto="63" class="range" style="display: none;">(Range11.42-24.80)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="29" sizefrominch="11.42" sizetoinch="24.80" sizeto="63" id="10116" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Back Length">Back Length</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="47" sizeto="105" class="range">(Range47-105)</span>
            <span data-id="10265" sizefrom="47" sizeto="105" class="range" style="display: none;">(Range18.50-41.34)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="47" sizefrominch="18.50" sizetoinch="41.34" sizeto="105" id="10117" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
        <dd class="star" onselectstart="return false;" unselectable="on">
            <span class="s1 star" title="Front Waist Length">Front Waist Length</span>
            <span class="solon">:</span>
            <span data-id="10266" sizefrom="31" sizeto="75" class="range">(Range31-75)</span>
            <span data-id="10265" sizefrom="31" sizeto="75" class="range" style="display: none;">(Range12.20-29.53)</span>
            <input type="text" maxlength="6" value="" cloth-id="3" sizefrom="31" sizefrominch="12.20" sizetoinch="29.53" sizeto="75" id="10172" inchvalue="" cmvalue="" data-map="sizeMap">
            <span class="unit">cm</span>
        </dd>
    </dl>

</div>